theme: jekyll-theme-architect
layout: post
title: blogthedistance
author: generic blog title
email: ron913422@gmail.com
description: Ramblings about and without life
twitter_username: breadboxron
github_username: ronthedistance
